### ISSUE TITLE
Explanation from youtube video

### ISSUE THREAD

**Issue by wind57** [AberonMan/spring-early-init-demo#1]

**Comment by 804** [comment]
Hello! 

Thanks a lot for your question and attention you payed to our meetup.

Yes, I absolutely agree with your comment. Our purpose was to show that starting `GenericFactoryBeanApplication` can't lead to `NullPointerException` inside `PokemonFactoryBean::getObject`. But you're right , there was no any `PokemonFactoryBean::getObject` call. So we need to improve our `GenericFactoryBeanApplication` demo part with configuring some new bean with our `Pokemon` beans as dependencies. It will be fair enough, such configuration leads to `PokemonFactoryBean::getObject` call.
